# Generated by Django 5.0 on 2023-12-09 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_historicalperformance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalperformance',
            old_name='average_response_time',
            new_name='avg_response_time',
        ),
    ]
