# Generated by Django 5.0 on 2023-12-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_average_response_time_historicalperformance_avg_response_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperformance',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
