# Generated by Django 5.0 on 2023-12-14 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_purchaseorder_issue_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='acknowledgement_date',
            new_name='acknowledgment_date',
        ),
    ]
